platform :ios, '8.0' #手机的系统

project ‘StatTender/StatTender.xcodeproj'

target ’StatTender’ do
    
pod 'AVOSCloud'               # 数据存储、短信、云引擎调用等基础服务模块
pod 'AVOSCloudIM'             # 实时通信模块
pod 'AVOSCloudCrashReporting' # 错误报告模块
pod 'MJExtension', '~> 3.0.13'# 看
pod 'Masonry'

end


